version: '3'
services:
  envoygateway:
    container_name: envoygateway
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem
  coffeeapi:
    container_name: coffeeapi
    build: CoffeeAPI/
  #  ports:
    #  - "8080:80"
    #  - "8081:443"
    environment:
      # ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_URLS: "http://+"
      # ASPNETCORE_HTTPS_PORT: "8081"
      # ASPNETCORE_ENVIRONMENT: "Development"
    # volumes:
    #   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    #   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  teaapi:
    container_name: teaapi
    build: TeaAPI/
    # ports:
      # - "8082:80"
      # - "8083:443"
    environment:
      # ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_URLS: "http://+"
      # ASPNETCORE_HTTPS_PORT: "8083"
      # ASPNETCORE_ENVIRONMENT: "Development"
    # volumes:
    #   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    #   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  juicegrpcservice:
    container_name: juicegrpcservice
    build: JuiceGrpcService/
    ports:
      - "8084:80"
      # - "8085:443"
    environment:
      # ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_URLS: "http://+"
      # ASPNETCORE_HTTPS_PORT: "8085"
      # ASPNETCORE_ENVIRONMENT: "Development"
    # volumes:
    #   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    #   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  apigwocelot:
    container_name: apigwocelot
    build: ApiGwOcelot/
    ports:
      - "7000:80"
      # - "8083:443"
    environment:
      # ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_URLS: "http://+"
      # ASPNETCORE_HTTPS_PORT: "8083"
      # ASPNETCORE_ENVIRONMENT: "Development"
    # volumes:
    #   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    #   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/